development:
  adapter: postgresql
  encoding: utf8
  database: camping_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: camping_test
  pool: 5
  username: 
  password:

