# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d9fc08dc921b1c4893c85adbf928c331b06f573cd0b516516e217a17934534d11fa70a984d5c15c71d8d67e4dc29f6f03cb379feb50fd0cca4e0aeb2baae4ed

test:
  secret_key_base: 5e6f3f39bc03b6fdc5c871da3a5f9a42b74ced789c35cb4ed1e46fcc869c1e3f00e284fcf456bcac81e266793308d3404179abb705db2cee673a098eff58f8e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
